apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custodian-manager
  labels:
    gitops.ownedBy: apps-custodian
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: apps-custodian
  source:
    path: environments/overlays/tools/argocd/apps
    repoURL: https://github.com/85matthew/custodian-ops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
