apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - ../../../../../manifests/tools/argocd/base

commonLabels:
  gitops.ownedBy: apps-custodian

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: custodian-dev
    path: patch-project.yaml

#  - target:
#      group: argoproj.io
#      version: v1alpha1
#      kind: Application
#      name: custodian-test
#    path: patch-project.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: custodian-prod
    path: patch-project.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: custodian-cicd
    path: patch-project.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: product-catalog-monitor
    path: patch-project.yaml