apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: custodian-cicd

bases:
#  - ../../../manifests/tekton/pipelines/push-prod-pr/base/
#  # Nexus
#  - https://github.com/redhat-canada-gitops/catalog/nexus2/base
  # Sonarqube
#  - https://github.com/redhat-canada-gitops/catalog/sonarqube8/overlays/plugins

# Pipeline

#  - https://github.com/85matthew/custodian-policies/.tekton/overlays/pipeline
  - https://github.com/85matthew/pipeline-catalog/packaged/custodian-pipeline-with-hook/base/?ref=iterate-on-pipeline-catalog
resources:
  - namespace.yaml

patches:
  - path: patch-container-repo.yaml
    target:
      kind: TriggerTemplate
      name: triggertemplate
      version: triggers.tekton.dev/v1alpha1
