apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - ../../../../environments/overlays/cicd

resources:
  - sealed-quaysecret.yml
  - sealed-githubsecret.yml

