apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../environments/overlays/cicd

resources:
  - sealed-quaysecret.yml
  - sealed-githubsecret.yml

patches:
  - path: patch-aws-iam-role.yaml
    target:
      kind: ServiceAccount
      name: pipeline
      version: v1
