apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quay-user-pass
  namespace: custodian-prod
spec:
  encryptedData:
    password: AgBUzI8lYD+Vp9gbA4TvkQyS3hSrbSNTe13CyHWvlfLLaILjnJwIRYtMIjmfKueyOl4LnXcuIfb/zPkKE5J6231vuEc367KX/zFU8wzhW1p7mBJKdVeq7KhDlxp4Iya93FU4kX2CONzpQmiP77iOh6FNthGbvOT8RwbFG+h3Nmr5XVa+bP6I3X2+c3f1u1IHcvZgy5gitiVg85E2TImlkLnZx0ed1aY8l6cS63ych2bnP5Ag5EQSB1wnM75SaJhQazzKSF6RJzsw+M7uUFXbxMQcKwSZpoIqfUtD5eHQKBkVW48MZKJCzxtAmlZXT3E5DvkF1KcBz+Q3avblvkFisKvWZUiUN9sBAV1Irmh/HxY/ig43KsgTiKAcoj0raohHkyTMO23qXa54/NlKL3SvMo3zNim2gG1g01TBu4nA3Su8gAxm7cemPZO9gIy3V4EWu/Ux8cG7EI0vtBlPo5cUe4xbyoi+gSNSTrRfeDdy1jKxaFJQAMRFG7krrzKoVUi682FmbwTwxbSRuYlyoEaFYG8A8MHMVjJyNjRaCRI0N80Fe8c8fNVME3ovUfLNqHZafLn0FHIFk7Cn1jYkarbCpEdZrSiLPCSJLNRDOiQ92RjQw+q+vI9GF47i80jEo8O5NBhwoT0OuVNQpUkj5wds8NYcc/RYZ02vIRi0AQBIqp2vgoYUz0W3QCZxhYoNe29Ri6bQzvh0JzR8pVq+oBbEHCxqVXiepr7VnKxKzchmziUPyHOKBo2dv79q/FTKREgj1CXqukQtUuOh4Tadv2g4xYTS
    username: AgCATJEdO8O6zHQctcLr0q0CgElo26YVgQLnHCQE2pBDSrIDul0e8qhL16N5RwJfFoHNJ8xM3BrmjCzMi4boOu0ssl/jjlfRxe7WWfw4jHf+zX1X/NYm713BVOz/uzYtOIXPuxWFcFwcUT6UgcQuPW5bXpbeitho32aQOHquW+v/inqJGL0592RviXDcEaV7rIBF9NP1aB2f6RBNCxJQDibn3TczxzUTClHp20PC6lfG3aTAYAvsYC+ilt0wPhokIZnM0tfqmnN1/sdAV0rx84oxWDFfQivrbHWIy3w3phXhmye2Hll3Wx8FRm/Y+Jt1rv6PrLiDMiP+w0/UqvcAebtXEC4Lx+r4cgsFHZLwhppRR6XIyyOETYGgaRQvM7fU947lU2ZcGGda4BjSj/fHNtrGqrv/1RuM8wq/hgTYXMJ6SXK2LjbtxQ2gXmMxhedNprFL+NUaeqJ5yiXx8dhfFuG+/oaW6lbMBMg0sJh4W/Y6IV61oCLtR5k6CGRJMQquS9ne9IkPTyXDkc0yYer3ijcbUa/6ybOkC+5gEcc4zSmqI28W+z/7KSrq0kEJ0MJkPynzIfbF6c5y6SGU750p1+uhu90rNcltvvBN8kQ3fUJsrytPU5ys3avLGZl/Mno/qb+fNjC0Y4DXCT3E508DNcqEzC/2+Tuwih7ptsEG2rl7NQM9//6dl4q9Aqgqc2f3hiJRcPBPp0sl3GV9pCYF6a7i7g==
  template:
    metadata:
      annotations:
        tekton.dev/docker-0: https://quay.io
      creationTimestamp: null
      name: quay-user-pass
      namespace: custodian-prod
    type: kubernetes.io/basic-auth

