apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: custodian-cicd
spec:
  encryptedData:
    password: AgCQtfQyggMfgwZ8PXSQpla2tyL+/uDx3LT05eKjnfk3KlTzTpdDgldAizXxRmycMLb3t3c0tXnTypNdcH5X4OeAtlpCDg6phGYmKTquOTtMMCvlD0kvG8F0SlEAMV+PTSTfjIx/5MguoBQ2kIztGZS4BSrtTsQHrkTecQFyqNalV/pasg3a92O+RXasDu7kORwC0kZEu9gPguOlxiLDjRxhQ1b5u/iHtEQnDC1yNFwmaOnbcT5SGpveUq7ZOZ6IwCFIphLqsE/WwTE3P9Aq1E6HsYtwlVf0PAnETQO2t3SC6MVHVqMhevraZOnRYx221xHScX1UeBYuPuDJy6iLysNjABF/tIeW5VVd71URchTNJ2XElbbihu+C6g72NYC2kOpgsRYbwjOTHJSGwtGlDBWa3yR1fS7nNy9EABHe0W76rIv9LHC3EDD0HUxUF9IRwQyStmK6yXVSrCsVjr2QMdkvyxmW5VeAq0ebgpCqBeD4KFgcq0epgwnugW2aC74aS0YVZHxojqtmCsDETgVZlcKFLWSXevqwfi3HZqNHrhEPK271o88Vvi/zk59kZ+vBsoD7PWs6x/JWH21KE6IyUBmRqMtHX9YG5C2EAj6TemZdO7a/puNdAom0ilj9xYAlycFskQ+S6JvCSDt8VngLPL9Gw5BO1CMNfQ65w+PwoGaIYsx/OOfTNVgS5V6FJMSqp9eUD5QFVIlEqcYeabGCg+psCYwyDd0LbtJOlKuFeoQ+u8JZG/tvn8rl
    username: AgBxR9wD3DyVM/+dyJs7FbR5PF0i0JJpplJMNASvdT4uzKjk9H5kLO4xShykWGT+nWtJ7vBN3Zi7SU0c5OUvj8mfYllziY+MDem3xdXyh4j1hF0cW8ttpctJWdyAlOv6A6tsfMe7a+ywrvAiFw/n/l+yMz/U5ObdfQaq+q4dD4ghukcV2k8MBLG5NMcbl7oWh1uk2dFuD24YaURM9tg+lSKbhLndP0s07OCiDdLmmpLcoTRMxnTcm5M09xznZZ39dzsNDbhNEMVwlZScaWPIc9so9/UgcTYfSKuVkOCZmUUeTTIJqkrLCCDggTZeLUXPrBBedk1Qwn31pga20wJ0fM7iawl8+gCq1Hl9dimGs0USfA3EwgaTn59x32vxgNAQJ17IeX8wfruV8naozT5tcGcx1BBATJb1+NVGIQoVk2v8zOH1/oouEtqmxv2cd/dJnDc8ZbtiLGmvHrvoancW8wrWI9+WakCNew200tbIgPaGAokGewBhPFKDN6i4GiVSG9YrOsYD7xjBGATq7aSP5ll74lhOnhxK6Sr7BczoAUMcuHWXq/rFZJo+ARYpNOfOrTi9jb5KQvVMTGeyeeiZbjXPCegWAII70N6XN6OqH7hVN02S0iM9TUWxgQw33M6v4kO7B0U7xSw2htgRdmyAnoOOVe9SqqMqlVopmacUmuuQpHKYFlSkSjJJnozxBKWBAsIQN9Ird5X670g=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: github-secret
      namespace: custodian-cicd
    type: kubernetes.io/basic-auth

