apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: custodian-prod

bases:
  - ../../../manifests/app/custodian/base/

resources:
  - namespace.yaml

patchesStrategicMerge:
  - patch-cron.yaml
