apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: custodian-cron
spec:
  schedule: "* 6,18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: custodian-cron
              image: quay.io/85matthew/custodian:stable
          restartPolicy: Never
          serviceAccountName: custodian-sa
