apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custodian-monitor
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: apps-custodian
  source:
    path: manifests/app/overlays/prod-quay
    repoURL: https://github.com/85matthew/custodian-ops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: route.openshift.io
      kind: Route
      jsonPointers:
        - /status/ingress
